encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.title, name="title"),
    path("newpage/", views.newPage, name="newPage"),
    path("wiki/<str:title>/editPage", views.editPage, name="editPage"),
    path("randomPage/", views.randomPage, name="randomPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.core.files.base import ContentFile
from django.http.response import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import redirect, render
from django import forms
from django.urls import reverse
import random
import markdown2

from . import util


def index(request):
    #If nothing is searched (No request is made)
    if request.POST.get("title") is not None:
        return newPage(request)
    elif request.GET.get("q") is None:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })
    #If something is searched (A request is made)
    else:
        return search(request)

def title(request, title):
    #For search box 
    if not request.GET.get("q") is None:
        return search(request)

    #For updating entry
    if request.POST.get("title"):
        util.save_entry(title, request.POST.get("content"))

    #Main function
    if util.get_entry(title) is None:  
        return HttpResponseNotFound("ERROR: Requested page was not found") #If no entry exists, head to error page
    else:
        return render(request, "encyclopedia/wiki.html", { #If entry exists, show that entry
            "title": title,
            "content": markdown2.markdown(util.get_entry(title))
        })

def search(request): 
    #If something is searched (A request is made)
    title = request.GET.get("q")

    #If exact same word exists
    if util.get_entry(title):                
        return render(request, "encyclopedia/wiki.html", { 
            "title": title,
            "content": markdown2.markdown(util.get_entry(title))
        })
        
    #If exact same word does not exist
    else:
        entries = util.list_entries()
        list=[]
        for entry in entries:
            if title.lower() in entry.lower():
                list.append(entry)
                    
        return render(request, "encyclopedia/search.html", {
            "entries" : list
        })

def newPage(request):
    # For searching
    if request.GET.get("q"):
        return search(request)
    
    if request.POST.get("title") is None:
        return render(request, "encyclopedia/newPage.html")
    else:
        title = request.POST.get("title")
        content = request.POST.get("content")

        entries = util.list_entries()
        for entry in entries:
            if title.lower() in entry.lower():
                return HttpResponseNotFound("ERROR: Title already exists")

        util.save_entry(title, content)
        return redirect("wiki:title", title=title) 


def editPage(request ,title):

    # For searching
    if request.GET.get("q"):
        return search(request)

    if util.get_entry(title) is None:
        return HttpResponseNotFound("ERROR: Requested page was not found")
    else:
        return render(request, "encyclopedia/editPage.html",{
            "title": title,
            "content": util.get_entry(title)
        })

def randomPage(request):
    # For searching
    if request.GET.get("q"):
        return search(request)

    entries = util.list_entries()
    rand = random.choice(entries)
    return redirect("wiki:title", title=rand)

encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>

    <form action="/wiki/{{title}}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="title"> Title </label>
                <input type="text" value="{{title}}" id="title" class="form-control" name="title" placeholder="Enter Title" autocomplete="off">
            </div>       
        </div>
        <div class="form-group">
            <label for="content"> Content </label>
            <textarea id="content" class="form-control" rows="10" name="content" style="max-width: 80%;">{{content}}</textarea>
        </div>
        <input type="submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href = "wiki/{{entry}}"> {{ entry }} </a> </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
          
                <form action="" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off" id="form">
                </form>
        
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newPage' %}"> Create New Page </a>
                </div>
                <div>
                    <a href="{% url 'wiki:randomPage' %}"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <form action="/" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="title"> Title </label>
                <input type="text" id="title" class="form-control" name="title" placeholder="Enter Title" autocomplete="off">
            </div>       
        </div>
        <div class="form-group">
            <label for="content"> Content </label>
            <textarea id="content" class="form-control" rows="8" name="content" style="max-width: 80%;"> </textarea>
        </div>
        <input type="submit" value="Save">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Result
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href = "/wiki/{{entry}}"> {{ entry }} </a> </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <!-- <a href="url 'wiki:editPage' title={{title}}"> Edit Page </a> -->
    <a href="/wiki/{{title}}/editPage"> Edit Page </a>
    <div>
        {{ content|safe }}
    </div>  
{% endblock %}